### ISSUE TITLE
DEBUG is set to True for Production server

### ISSUE THREAD

**Issue by debdutgoswami** [PragatiVerma18/Snippet-Share#39]
**Describe the bug**

Django apps should not be deployed with `DEBUG=True` and `SECRET_KEY` should be taken from an enviornment variable.

**To Reproduce**
Any error on the production server will trigger this. For instance reproducing issue #38 will trigger the same.

**Expected behavior**
Even if something breaks in prodcution (which is very common for side projects), you would idealy want to show a custom page or something, even configuring `nginx` will give you a default page for the same.

**Screenshots**
Refer to issue #38 

**Desktop (please complete the following information):**
 - OS: All
 - Browser: All

**Smartphone (please complete the following information):**
 - Device: All
 - OS: All
 - Browser: All

**Comment by PragatiVerma18** [comment]
@debdutgoswami would you like to send in a PR for this issue?

**Comment by debdutgoswami** [comment]
Sure. I'll drop a PR
