### ISSUE TITLE
invalid username also get accpeted

### ISSUE THREAD

**Issue by anjali1102** [PragatiVerma18/Snippet-Share#40]
![njack_issue](https://user-images.githubusercontent.com/56559378/101194279-c9409280-3683-11eb-99cd-dd8c621f38c4.png)
SIGN UP with USERNAME (eg  ".",  " /",  "< ") is getting ACCEPTED
there should be some CRITERIA OF VALID USERNAME

**Comment by Kibby-b** [comment]
Can you assign this issue to me?

**Comment by devsTudu** [comment]
Is the issue still there, I can give it a try to solve it
Thank You

**Comment by Kibby-b** [comment]
Hi! I have already devoted my time to this issue and resolved it. Was just going to make a PR.

**Comment by PragatiVerma18** [comment]
@Kibby-b thanks for your time. Can you please send in a PR to the `nwoc` branch?
