### ISSUE TITLE
Code of Conduct

### ISSUE THREAD

**Issue by Tejas1510** [PragatiVerma18/Snippet-Share#41]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
A code of conduct file is missing
So can I work on it @9916103020 

**Describe alternatives you've considered**

**Additional context**

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by PragatiVerma18** [comment]
@Tejas1510  go ahead, and please remember to make the PR to `nwoc` branch.

**Comment by Tejas1510** [comment]
Sure @PragatiVerma18
