### ISSUE TITLE
Add contributing.md file

### ISSUE THREAD

**Issue by Kerveyfelix** [PragatiVerma18/Snippet-Share#42]
Is your feature request related to a problem? Please describe.
Sometimes its confusing about how to get started with open source and contribute in a project as a beginer.

Describe the solution you'd like
Add contributing.md file which contains tutorial to make pull request from scratch, general guidelines for contribution, and some rules.

Describe alternatives you've considered
Updating README.md but it looks very chaotic

Additional context
Can I work on this feature?

**Comment by yashgautam9274** [comment]
I want to work on this issue

**Comment by PragatiVerma18** [comment]
@Kerveyfelix go ahead, and please remember to make the PR to `nwoc` branch.

**Comment by Kerveyfelix** [comment]
Will keep this in mind. Thanks.
