### ISSUE TITLE
Set Up discussion feature for great conversion.

### ISSUE THREAD

**Issue by Vishal-raj-1** [PragatiVerma18/Snippet-Share#43]
@PragatiVerma18 mam , Did you see new feature on github ? We can set discussion on this repo. So what you have to do is just click this block in setting section of your repo. It's Amazing I guess. Have a try.

![discussion](https://user-images.githubusercontent.com/59874304/101589985-8c6ff500-3a0f-11eb-8756-48b53dfe1adf.JPG)

One more thing there is one mind blowing event Github Universe is running. You must watch those events.

**Comment by PragatiVerma18** [comment]
Thanks for the updates @Vishal-raj-1 ! Really appreciate it 😄

**Comment by PragatiVerma18** [comment]
Get started with discussions here: [https://github.com/PragatiVerma18/Snippet-Share/discussions](https://github.com/PragatiVerma18/Snippet-Share/discussions)

**Comment by Vishal-raj-1** [comment]
@PragatiVerma18 did you update my point to `+9` for opening two issues and one PR !!
