### ISSUE TITLE
Welcome bot integration

### ISSUE THREAD

**Issue by Sloth-Panda** [PragatiVerma18/Snippet-Share#66]
Hello there,
I can add a welcome bot config file having a proper message that will show up when any user will open up an issue or pull-request for the first time as a part of SWOC. 
For reference, kindly check out: https://github.com/apps/welcome

**Comment by PragatiVerma18** [comment]
Hi @Sloth-Panda you can go ahead and create a PR for this issue!

**Comment by Sloth-Panda** [comment]
@PragatiVerma18  kindly add swoc tag and review the pr too

**Comment by Sloth-Panda** [comment]
@PragatiVerma18  can you add swoc and other relevant tags to it and the closed pr related to this issue
