### ISSUE TITLE
Mobile version layout

### ISSUE THREAD

**Issue by dhairyaostwal** [PragatiVerma18/Snippet-Share#67]
@PragatiVerma18 I found a bug on the mobile version of the app.

If you could provide me the file location I would love to help contribute in this project. I request you to kindly consider my request and give me an opportunity to contribute. Much thanks :)

![Screen Shot 2021-01-18 at 12 25 13](https://user-images.githubusercontent.com/50984984/104882011-5451bf80-5988-11eb-9ac2-6888004f68a3.png)

**Comment by PragatiVerma18** [comment]
Hi @dhairyaostwal, you can go ahead and explore the codebase and create a PR to fix the issue that you found. Just a thing, please drop a comment explaining what are you planning to do?
