### ISSUE TITLE
Error Occurs While Submiting Snip

### ISSUE THREAD

**Issue by piyush-pk** [PragatiVerma18/Snippet-Share#68]
**Describe the bug**
Your Github Repository Of Snippet-Share Project Has Some Error.
This is One Of Them If We Submit Our Form/Snip And Again We Create New Snip But Here We Select Again Same **Syntax Highlighting** Then Here An Error occurs Which is **_MultiValueDictKeyErrpr_**. I can easily solve it if you assign me.

**To Reproduce**
1. Go to 'https://snip-share.herokuapp.com/'
2. Click on 'Submit After Filling Snip Details'
3. Again Submit With Same Syntax Highlighting
4. See an error

**Expected behavior**
After Error Occurs We Can't be able to Create New Snip.

**Screenshots**
![Screenshot (11)](https://user-images.githubusercontent.com/55063039/105081425-2e2b3d00-5ab8-11eb-8d2e-da6d3f7d3b15.png)
![30896c96-f472-4a0d-b5fd-17dab18c585d](https://user-images.githubusercontent.com/55063039/105081441-35eae180-5ab8-11eb-87ca-102f49316d3f.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 87.0.4280.141

**Additional context**
Some Times Snip DoesNotExist Error Occurs.

**Comment by PragatiVerma18** [comment]
Hi @piyush-pk, thanks for pointing it out. Will you be working on it?

**Comment by piyush-pk** [comment]
Yes @PragatiVerma18,  i will work if You Assign Me.

**Comment by piyush-pk** [comment]
hey @PragatiVerma18, i have solved this error. if You Assign me So That I Can Make Pull Request.

**Comment by iihsan** [comment]
Hi, I've fixed that issue, and created a pull request as well, just waiting for collaborators to approve.
