### ISSUE TITLE
Make Rest APIs

### ISSUE THREAD

**Issue by PragatiVerma18** [PragatiVerma18/Snippet-Share#8]
### Create APIs to `get` / `post` data i.e. code snippets along with required details.

> Recommended to use Django Rest Framework.

#### Tasks to Do:

-  Define the JSON structure of the data

-  Create GET / POST routes

 - Provide a Postman collection to test the APIs

> You can also use Heroku/AWS/GCP/Azure. Please ask for approval first.

### Student Code-In 
- Please add the label `SCI` for issues that are made during Student Code-In and are meant for SCI participants only.
- Please make a PR to the `SCI` branch only, contributions to the `master` branch would not be accepted.

**Comment by abhishekgupta368** [comment]
I will do it.

**Comment by pawankm21** [comment]
Is this still open? if yes then assign it to me

**Comment by PragatiVerma18** [comment]
It's completed, look for some other issue @pawankm21
